webtalk_init -webtalk_dir C:/Users/chris/OneDrive/Desktop/project_1/project_1.sim/sim_1/synth/timing/xsim/xsim.dir/testbench_time_synth/webtalk/
webtalk_register_client -client project
webtalk_add_data -client project -key date_generated -value "Wed Dec  4 19:51:31 2019" -context "software_version_and_target_device"
webtalk_add_data -client project -key product_version -value "XSIM v2019.2 (64-bit)" -context "software_version_and_target_device"
webtalk_add_data -client project -key build_version -value "2700185" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_platform -value "WIN64" -context "software_version_and_target_device"
webtalk_add_data -client project -key registration_id -value "" -context "software_version_and_target_device"
webtalk_add_data -client project -key tool_flow -value "xsim_vivado" -context "software_version_and_target_device"
webtalk_add_data -client project -key beta -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key route_design -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_family -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_device -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_package -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_speed -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key random_id -value "b31f1cb8-43b7-4b84-833f-58e2cc563bd5" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_id -value "e522bcb1ea5b4781b1a0cdbcb42ed167" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_iteration -value "173" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_name -value "Windows Server 2016 or Windows 10" -context "user_environment"
webtalk_add_data -client project -key os_release -value "major release  (build 9200)" -context "user_environment"
webtalk_add_data -client project -key cpu_name -value "Intel(R) Core(TM) i7-8550U CPU @ 1.80GHz" -context "user_environment"
webtalk_add_data -client project -key cpu_speed -value "1992 MHz" -context "user_environment"
webtalk_add_data -client project -key total_processors -value "1" -context "user_environment"
webtalk_add_data -client project -key system_ram -value "17.000 GB" -context "user_environment"
webtalk_register_client -client xsim
webtalk_add_data -client xsim -key Command -value "xsim" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key trace_waveform -value "true" -context "xsim\\usage"
webtalk_add_data -client xsim -key runtime -value "19412 ns" -context "xsim\\usage"
webtalk_add_data -client xsim -key iteration -value "0" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Time -value "0.14_sec" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Memory -value "7080_KB" -context "xsim\\usage"
webtalk_transmit -clientid 1135200588 -regid "" -xml C:/Users/chris/OneDrive/Desktop/project_1/project_1.sim/sim_1/synth/timing/xsim/xsim.dir/testbench_time_synth/webtalk/usage_statistics_ext_xsim.xml -html C:/Users/chris/OneDrive/Desktop/project_1/project_1.sim/sim_1/synth/timing/xsim/xsim.dir/testbench_time_synth/webtalk/usage_statistics_ext_xsim.html -wdm C:/Users/chris/OneDrive/Desktop/project_1/project_1.sim/sim_1/synth/timing/xsim/xsim.dir/testbench_time_synth/webtalk/usage_statistics_ext_xsim.wdm -intro "<H3>XSIM Usage Report</H3><BR>"
webtalk_terminate
